# Cognivern Backend-Only Docker Setup
# Trading Agent runs natively on host for full Node.js environment
version: "3.8"

services:
  cognivern-backend:
    build: .
    container_name: cognivern-backend
    restart: unless-stopped
    ports:
      - "10000:10000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=10000
      - CORS_ORIGIN=*
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cognivern-network

  nginx:
    image: nginx:alpine
    container_name: cognivern-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - cognivern-backend
    networks:
      - cognivern-network

networks:
  cognivern-network:
    driver: bridge
