services:
  - type: web
    name: escheat-agents
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Recall Configuration
      - key: RECALL_PRIVATE_KEY
        sync: false
      - key: RECALL_BUCKET_ALIAS
        sync: false
      - key: RECALL_NETWORK
        value: testnet
      # Security
      - key: API_KEY
        sync: false
      # Provider Configuration
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4
      # Governance Configuration
      - key: DEFAULT_POLICY
        value: standard
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
