services:
  - type: web
    name: escheat-agents
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Recall Configuration
      - key: RECALL_PRIVATE_KEY
        sync: false
      - key: RECALL_BUCKET_ADDRESS
        sync: false
      - key: RECALL_NETWORK
        value: testnet
      - key: RECALL_SYNC_INTERVAL
        value: 60000
      - key: RECALL_BATCH_SIZE
        value: 8
      # Security
      - key: API_KEY
        sync: false
      # Provider Configuration
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4
      # Governance Configuration
      - key: DEFAULT_POLICY
        value: standard
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 70
      targetCPUPercent: 70
