# Prometheus configuration for Cognivern
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Cognivern API metrics
  - job_name: "cognivern-api"
    static_configs:
      - targets: ["cognivern-api:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # System metrics
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
