module.exports = {
  apps: [
    {
      name: 'cognivern-backend',
      script: 'dist/index.js',
      cwd: '/opt/cognivern/app',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      kill_timeout: 5000,
      listen_timeout: 10000,
      node_args: '-r dotenv/config',
      env: {
        NODE_ENV: 'production',
        PORT: 10000,
        LOG_LEVEL: 'info',
        DOTENV_CONFIG_PATH: '/opt/cognivern/shared/.env',
        CRE_RUNS_FILE: '/opt/cognivern/shared/data/cre-runs.jsonl',
        UX_EVENTS_FILE: '/opt/cognivern/shared/data/ux-events.jsonl',
        IDEMPOTENCY_STORE_FILE: '/opt/cognivern/shared/data/idempotency-store.json',
        OWS_VAULT_PATH: '/opt/cognivern/shared/data/ows-vault.json',
        COGNIVERN_TOKEN_TELEMETRY_FILE: '/opt/cognivern/shared/data/token-telemetry.json',
        COGNIVERN_USAGE_FILE: '/opt/cognivern/shared/data/usage.json',
      },
      log_file: '/opt/cognivern/shared/logs/combined.log',
      out_file: '/opt/cognivern/shared/logs/out.log',
      error_file: '/opt/cognivern/shared/logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      max_size: '10M',
    }
  ],
};
